### ISSUE TITLE
Invalid links to javascript and css files for rails 4.2

### ISSUE THREAD

**Issue by ests** [josevalim/rails-footnotes#127]
I've just installed gem with default config. The links to controllers and views are working very well. 
But all links to .js and .css files are invalid, and so, cannot be opened:

```
mvim://open?url=file:///Users/ernest/code/work/ipm_texted/public/assets/application.js&line=1&column=1
```

Note that `app` has been replaced by `public`.

I believe that the reason is [here](https://github.com/josevalim/rails-footnotes/blob/master/lib/rails-footnotes/notes/files_note.rb#L31).

This is because `Rails.application.config.assets[:enabled]` is (in out of the box generated rails app) `nil`. The quick fix is to set `config.assets[:enabled] = true` in you development env., but maybe there's a better solution?

**Comment by msroot** [comment]
+1

**Comment by Intrepidd** [comment]
Thanks for reporting this. I'm currently on vacation but I'll have a look
as soon as I can.

**Comment by Intrepidd** [comment]
Ok I had a look and this part of the code is quite old (still supports pre-asset-pipeline), untested and now buggy (``config.assets.enabled`` is not used anymore, starting from rails 4 IIRC), but the good new is now that I dropped support for Rails < 3.2, I'll be able to drop some code, refactor it, and above all write some tests.

ETA next monday since I'm still on vacations.

**Comment by msroot** [comment]
removing ```Rails.application.config.assets[:enabled]``` is working fine now!

**Comment by Intrepidd** [comment]
I just pushed rails-footnotes 4.1.6 with a fix for this issue :)
